name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Copy README.md into project folder
        run: cp README.md SVGCreator/README.md
        
      - name: Make sure project folder exists
        run: mkdir -p SVGCreator/SVGCreator/bin/Release/net8.0/

      - name: Copy README.md into project folder again
        run: cp README.md SVGCreator/SVGCreator/bin/Release/net8.0/

      - name: Build
        run: dotnet build --configuration Release --no-restore
        

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build -o ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
